// ---------- Prompt List ----------

export const prompts = [

"Explain why you are banned from a restaurant.",
"Write a terrible excuse for being late.",
"Explain why your neighbor is suspicious.",
"Write a message found inside a mysterious box.",
"Explain why you should be the next king.",
"Describe your evil plan.",
"Explain why your plan failed.",
"Write an apology to everyone in the room.",
"Explain why you cannot be trusted.",
"Write a warning to future generations.",

"Explain why your pet became famous.",
"Describe your most embarrassing achievement.",
"Explain why you were removed from a competition.",
"Write a message from your evil twin.",
"Explain why you accidentally saved the world.",
"Describe your secret identity.",
"Explain why you are hiding in a bathroom.",
"Write a complaint about your own life.",
"Explain why you challenged a wizard.",
"Describe your greatest discovery.",

"Write a message from a confused alien.",
"Explain why aliens should avoid Earth.",
"Describe your new invention.",
"Explain why your invention is dangerous.",
"Write instructions for using a ridiculous machine.",
"Explain why your robot malfunctioned.",
"Describe your dream vacation gone wrong.",
"Explain why you cannot leave your house.",
"Write a letter from your future self.",
"Explain why your future self is disappointed.",

"Describe your fantasy kingdom.",
"Explain why your castle has a strange rule.",
"Write an announcement from a king.",
"Explain why the dragon chose you.",
"Describe your legendary weapon.",
"Explain why your sword is embarrassing.",
"Write a message from a magical creature.",
"Explain why you joined a quest.",
"Describe your unusual magical power.",
"Explain why your spell failed.",

"Write a pirate captain's announcement.",
"Explain why your pirate crew quit.",
"Describe your hidden treasure.",
"Explain why your treasure is worthless.",
"Write a message found in a bottle.",
"Explain why you became a pirate.",
"Describe your worst adventure.",
"Explain why your ship disappeared.",
"Write a pirate's apology letter.",
"Explain why you were kicked off your ship.",

"Describe your strange new business.",
"Explain why nobody should buy your product.",
"Write an advertisement for something ridiculous.",
"Explain why your company went bankrupt.",
"Describe your terrible invention idea.",
"Write a five-star review for something awful.",
"Explain why your restaurant failed.",
"Describe your unusual job.",
"Explain why you were fired.",
"Write a message to your angry customers.",

"Explain why you are being chased.",
"Describe your escape plan.",
"Write a message to your enemy.",
"Explain why your enemy became your friend.",
"Describe your secret hideout.",
"Explain why your hiding place was discovered.",
"Write a villain's speech.",
"Explain why you became a villain.",
"Describe your heroic comeback.",
"Explain why everyone misunderstood you.",

"Write a message from a ghost.",
"Explain why a ghost is bothering you.",
"Describe your haunted house.",
"Explain why the monster is friendly.",
"Write a monster's diary entry.",
"Explain why you adopted a monster.",
"Describe your strangest roommate.",
"Explain why your house moved.",
"Write a message from a talking animal.",
"Explain why animals are angry.",

"Describe your weirdest dream.",
"Explain why your dream became real.",
"Write a message from the moon.",
"Explain why the moon is upset.",
"Describe your trip through space.",
"Explain why your spaceship crashed.",
"Write a message from another planet.",
"Explain why you cannot return home.",
"Describe your new planet.",
"Explain why your planet needs help.",

"Write a ridiculous excuse.",
"Explain why everyone is confused.",
"Describe your greatest failure.",
"Explain why you celebrated too early.",
"Write a dramatic announcement.",
"Explain why something completely normal became dangerous.",
"Describe your unusual hobby.",
"Explain why your hobby scares people.",
"Write a message to your younger self.",
"Explain why your younger self made a mistake."

];
