export const words = [
    // Nouns
    "apple", "banana", "pizza", "dragon", "wizard",
    "pirate", "robot", "alien", "ghost", "monster",
    "unicorn", "castle", "tower", "forest", "mountain",
    "river", "ocean", "island", "cave", "volcano",
    "moon", "star", "planet", "spaceship", "rocket",
    "computer", "phone", "book", "map", "key",
    "door", "chair", "table", "bed", "pillow",
    "blanket", "shoe", "hat", "sword", "shield",
    "helmet", "armor", "crown", "ring", "coin",
    "treasure", "diamond", "gold", "cookie", "cake",
    "sandwich", "taco", "cheese", "pickle", "chicken",
    "cow", "dog", "cat", "fish", "bird",
    "mouse", "frog", "horse", "dragonfly", "bee",
    "spider", "snake", "turtle", "tree", "flower",
    "leaf", "rock", "cloud", "storm", "fire",
    "water", "ice", "shadow", "light", "song",
    "dance", "movie", "game", "story", "letter",
    "picture", "camera", "paint", "toy", "ball",
    "rope", "box", "bag", "keyhole", "clock",
    "mirror", "mask", "king", "queen", "soldier",
    "captain", "doctor", "teacher",

    // Verbs
    "run", "jump", "walk", "fly", "swim",
    "climb", "crawl", "dance", "sing", "laugh",
    "cry", "smile", "shout", "whisper", "eat",
    "drink", "cook", "bake", "burn", "freeze",
    "explode", "break", "build", "create", "destroy",
    "fix", "throw", "catch", "kick", "punch",
    "push", "pull", "open", "close", "lock",
    "unlock", "find", "hide", "seek", "steal",
    "give", "take", "buy", "sell", "trade",
    "carry", "drop", "lift", "fall", "sleep",
    "wake", "dream", "think", "know", "forget",
    "remember", "learn", "teach", "read", "write",
    "draw", "paint", "play", "fight", "win",
    "lose", "help", "save", "attack", "defend",
    "protect", "escape", "chase", "follow", "lead",
    "become", "change", "grow", "shrink", "transform",
    "discover", "explore", "travel", "visit", "invent",
    "charge", "control", "summon", "wear", "remove",
    "mix", "spill",

    // Adjectives
    "tiny", "giant", "huge", "small", "purple",
    "green", "blue", "red", "golden", "silver",
    "ancient", "modern", "magical", "mysterious",
    "angry", "happy", "sad", "silly", "strange",
    "weird", "funny", "scary", "friendly", "evil",
    "good", "lazy", "fast", "slow", "loud",
    "quiet", "flying", "broken", "secret", "hidden",
    "bright", "dark", "cold", "hot", "spicy",
    "sweet", "sticky", "fuzzy", "sharp", "soft",
    "heavy", "light", "crazy", "wild", "royal",
    "legendary",

    // Connectors
    "the", "a", "an", "my", "your",
    "his", "her", "our", "their", "this",
    "that", "these", "those", "and", "or",
    "but", "because", "with", "without", "from",
    "to", "for", "at", "by", "about",
    "into", "inside", "outside", "over", "under",
    "through", "after", "before", "while", "when",
    "where", "who", "what", "how", "very",
    "really", "almost", "never", "always", "maybe",
    "not", "only", "also", "then", "so"
];


